In [1]:
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())
import pandas as pd
import time
import os

[WDM] -

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 106.0.5249
[WDM] - Get LATEST driver version for 106.0.5249
[WDM] - Driver [C:\Users\rr159\.wdm\drivers\chromedriver\win32\106.0.5249.61\chromedriver.exe] found in cache
C:\Users\rr159\AppData\Local\Temp/ipykernel_24000/3244778664.py:4: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())

#### Used the link of IndiaMart for Ceiling Titles

In [2]:
# driver.get method() will navigate to a page given by the URL address
driver.get("https://dir.indiamart.com/search.mp?ss=ceiling+tiles&src=as-popular%3Akwd%3Dceilingtiles%3Apos%3D1%3Acat%3D-2%3Amcat%3D-2")

### NOTE: To get the phone number of the retailer you need to login by phone no. and OTP. Then click on "See More Result" again and again to get more data at once.

In [4]:
from selenium.webdriver.common.by import By

storeDetails = driver.find_elements(By.XPATH, '//div[@class="dib pr to-txt-gn"]/span[@class="elps elps1"]')
names = driver.find_elements(By.XPATH, '//h4[@class="lcname tac"]/a[@class="clr3 fs12 fwn rsrc"]/span')

#To get the phonenumber of the retailer you need to login and OTP. Then click on See More Result
contactList = driver.find_elements(By.XPATH, '//span[@class="pns_h duet fwb"]')

nameList = []
addressList = []
numbersList = []

for i in range(len(names)):
    
    name = names[i].text
    address = storeDetails[i].text
    contact = contactList[i].text
    
    nameList.append(name)
    addressList.append(address)
    numbersList.append(contact)


    
# intialise data of lists.
data = {'Company Name':nameList,
        'Address': addressList,
        'Phone':numbersList
       }

# Create DataFrame
df = pd.DataFrame(data)
df

,Company Name,Address,Phone
0,FurniTech,"Gulbai Tekra, Ahmedabad",08048952247
1,Shri Giriraj Trading Co.,"Nangloi, New Delhi",08048607828
2,National Traders,"Mayapuri, New Delhi",08048989537
3,RJ Thermocol & Gypsum 2x2 Ceiling,"BRTS Road punagam, Surat",08046032686
4,Interiorz Hub,Delhi,07942564629
...,...,...,...
206,Paritosh Interior,"Teka Naka Kamptee Road, Nagpur",08048615608
207,Premier Claycut Integrators,"Bangalore, Bengaluru",07942545055
208,Jayswal Agencies,"R T Nagar Kanakanagar, Bengaluru",08046043500
209,New Design Interior,"Santacruz East, Mumbai",08046045080
210,M/s Goyal Enterprises,Ghaziabad,07942546750

In [11]:
df.reset_index(drop=True)

,Company Name,Address,Phone
0,FurniTech,"Gulbai Tekra, Ahmedabad",08048952247
1,Shri Giriraj Trading Co.,"Nangloi, New Delhi",08048607828
2,National Traders,"Mayapuri, New Delhi",08048989537
3,RJ Thermocol & Gypsum 2x2 Ceiling,"BRTS Road punagam, Surat",08046032686
4,Interiorz Hub,Delhi,07942564629
...,...,...,...
206,Paritosh Interior,"Teka Naka Kamptee Road, Nagpur",08048615608
207,Premier Claycut Integrators,"Bangalore, Bengaluru",07942545055
208,Jayswal Agencies,"R T Nagar Kanakanagar, Bengaluru",08046043500
209,New Design Interior,"Santacruz East, Mumbai",08046045080
210,M/s Goyal Enterprises,Ghaziabad,07942546750

In [14]:
df.to_csv('IndiaMart_ceiling-tile.csv',index=False)